name: Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0, v2.1.0, etc.

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build binaries
      run: |
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o httpie-to-postman-linux-amd64 main.go
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o httpie-to-postman-linux-arm64 main.go
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o httpie-to-postman-darwin-amd64 main.go
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o httpie-to-postman-darwin-arm64 main.go
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o httpie-to-postman-windows-amd64.exe main.go
        GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o httpie-to-postman-windows-arm64.exe main.go

    - name: Create checksums
      run: |
        sha256sum httpie-to-postman-* > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: Release ${{ steps.version.outputs.VERSION }}
        body: |
          ### HTTPie to Postman Converter ${{ steps.version.outputs.VERSION }}
          #### Checksums

          Verify your download using the checksums provided in `checksums.txt`.
        files: |
          httpie-to-postman-linux-amd64
          httpie-to-postman-linux-arm64
          httpie-to-postman-darwin-amd64
          httpie-to-postman-darwin-arm64
          httpie-to-postman-windows-amd64.exe
          httpie-to-postman-windows-arm64.exe
          checksums.txt
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
